name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout (com histórico completo para métricas)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Notify Sleuth via cURL (Solução para Erro 401)
        if: success()
        run: |
          # 1. Define a URL de Registro de Deploy do seu projeto
          SLEUTH_URL="https://app.sleuth.io/api/1/deployments/clarachence/tarefa-pipeline/register_deploy"
          
          # 2. Faz a chamada POST, garantindo que o token está no cabeçalho Authorization: Bearer
          # Isso é exatamente o que a tela de tokens do Sleuth recomenda para autenticação!
          curl -X POST "$SLEUTH_URL" \
            -H "Authorization: Bearer ${{ secrets.SLEUTH_DEPLOY_TOKEN }}" \
            -d "sha=${{ github.sha }}" \
            -d "environment=production"